(()=>{
'use strict';
const $=s=>document.querySelector(s),sel=$('#brief-date'),dateLabel=$('#brief-date-label'),reading=$('#reading-time'),nav=$('#section-nav'),status=$('#status'),content=$('#brief-content'),recordedPanel=$('#recorded-feedback-panel'),exportPanel=$('#export-panel'),overall=$('#general-feedback'),exportBtn=$('#export-feedback'),clearBtn=$('#clear-feedback'),exportStatus=$('#export-status');
const order=['paris_events','cs_ai','technical_idea','non_cs_science','geopolitics','signal_vs_noise','marxist_fragment','marxist_quote','philosophy_fragments','philosophy_politics','french_usage','french_note','french','music','unrelated_fact','puzzle','puzzle_dilemma'];
const titles={paris_events:'Paris events',cs_ai:'CS and AI developments',technical_idea:'Technical idea',non_cs_science:'Non-CS science',geopolitics:'Geopolitics and political economy',signal_vs_noise:'Signal versus noise',marxist_fragment:'Marxist fragment',marxist_quote:'Marxist fragment',philosophy_fragments:'Philosophy and political fragments',philosophy_politics:'Philosophy and political fragments',french_usage:'French usage',french_note:'French usage',french:'French usage',music:'Music corner',unrelated_fact:'Unrelated fact',puzzle:'Puzzle / dilemma',puzzle_dilemma:'Puzzle / dilemma'};
let archive,brief,recorded='',timer;
const key=d=>`gpt-daily-brief-feedback:${d}`;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const inline=v=>esc(v).replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/`([^`]+)`/g,'<code>$1</code>');
function md(s){let out=[],list=false;for(const raw of String(s||'').split(/\r?\n/)){const x=raw.trim();if(!x){if(list){out.push('</ul>');list=false}continue}let m=x.match(/^(#{1,4})\s+(.+)$/);if(m){if(list){out.push('</ul>');list=false}const n=Math.min(4,m[1].length+1);out.push(`<h${n}>${inline(m[2])}</h${n}>`);continue}m=x.match(/^[-*]\s+(.+)$/);if(m){if(!list){out.push('<ul>');list=true}out.push(`<li>${inline(m[1])}</li>`);continue}if(list){out.push('</ul>');list=false}out.push(`<p>${inline(x)}</p>`)}if(list)out.push('</ul>');return out.join('')}
const nullable=v=>{v=String(v||'').trim();return v||null};
function titleForDate(d){return `Daily Brief — ${new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${d}T12:00:00Z`))}`}
function yid(url){if(!url)return null;try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1)||null;if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2]||null;return u.searchParams.get('v')}catch{return null}}
function sources(a){if(!Array.isArray(a))return'';const x=a.filter(v=>typeof v==='string'&&/^https?:\/\//.test(v)).map((v,i)=>`<a href="${esc(v)}" target="_blank" rel="noopener noreferrer">Source ${i+1}</a>`);return x.length?`<p class="source-links">${x.join(' · ')}</p>`:''}
function val(v){if(v==null)return'';if(['string','number','boolean'].includes(typeof v))return`<p>${inline(v)}</p>`;if(Array.isArray(v))return`<ul>${v.map(x=>`<li>${typeof x==='object'?val(x):inline(x)}</li>`).join('')}</ul>`;return`<dl class="structured-list">${Object.entries(v).map(([k,x])=>`<div><dt>${inline(k.replaceAll('_',' '))}</dt><dd>${val(x)}</dd></div>`).join('')}</dl>`}
function music(v){const types=['classical','jazz','other'],label=t=>t==='jazz'?'Jazz':t==='other'?'Other':'Classical';if(Array.isArray(v))return v.slice(0,3).map((e,i)=>{const o=typeof e==='string'?{piece:e}:e||{},url=o.youtube_url||o.url||'';return{type:o.type||types[i]||`track_${i+1}`,label:o.label||label(o.type||types[i]),piece:o.piece||o.title||`Recommendation ${i+1}`,performer:o.performer||'',description:o.rating_note||o.description||'',url,videoId:yid(url),recordedRating:Number.isFinite(o.rating)?o.rating:null}});if(v&&typeof v==='object')return types.map(t=>{const e=v[t]??v[t==='other'?'different_lane':t];if(e==null)return null;if(typeof e==='string')return{type:t,label:label(t),piece:e,performer:'',description:'',url:'',videoId:null,recordedRating:null};const url=e.youtube_url||e.url||'';return{type:t,label:e.label||label(t),piece:e.piece||e.title||t,performer:e.performer||'',description:e.rating_note||e.description||'',url,videoId:yid(url),recordedRating:Number.isFinite(e.rating)?e.rating:null}}).filter(Boolean);return[]}
function canon(k){return k==='marxist_quote'?'marxist_fragment':k==='philosophy_politics'?'philosophy_fragments':k==='french'||k==='french_note'?'french_usage':k==='puzzle_dilemma'?'puzzle':k}
function details(v){if(!Array.isArray(v))return val(v);if(v.some(x=>x&&typeof x==='object'&&(x.title||x.summary)))return v.map(x=>`<h3>${inline(x.title||'Item')}</h3>${x.summary?`<p>${inline(x.summary)}</p>`:''}${sources(x.sources)}`).join('');return val(v)}
function sectionFrom(item,n){const id=canon(item.section),base=titles[id]||item.title||id.replaceAll('_',' ');if(id==='music'){const rec=item.recommendations||item.items||item.music||[];return{id,number:n,title:base,content:item.summary?`<p>${inline(item.summary)}</p>`:'',queue:item.combined_queue||item.queue||'',items:music(rec)}}return{id,number:n,title:item.title?`${base}: ${item.title}`:base,content:`${item.summary?`<p>${inline(item.summary)}</p>`:''}${item.items?details(item.items):''}${sources(item.sources)}`}}
function normalise(raw){const full=Array.isArray(raw.sections)&&raw.sections.every(s=>s&&typeof s.id==='string'&&typeof s.content==='string');if(full)return raw;let sections=[];if(Array.isArray(raw.items)){const g=new Map;raw.items.forEach(x=>{if(!g.has(x.section))g.set(x.section,[]);g.get(x.section).push(x)});let n=1;for(const k of order){const a=g.get(k);if(!a)continue;if(a.length===1)sections.push(sectionFrom(a[0],n++));else sections.push({id:canon(k),number:n++,title:titles[k]||k.replaceAll('_',' '),content:a.map(x=>`<h3>${inline(x.title||'Item')}</h3>${x.summary?`<p>${inline(x.summary)}</p>`:''}${sources(x.sources)}`).join('')})}}else if(Array.isArray(raw.sections)){let n=1;raw.sections.forEach(x=>{if(x&&x.section)sections.push(sectionFrom(x,n++))})}else if(raw.sections&&typeof raw.sections==='object'){let n=1;for(const k of order){if(!(k in raw.sections))continue;const id=canon(k),v=raw.sections[k];sections.push(id==='music'?{id,number:n++,title:titles[id],content:'',queue:v?.combined_queue||v?.queue||'',items:music(v)}:{id,number:n++,title:titles[id]||id.replaceAll('_',' '),content:val(v)})}}
const top=Array.isArray(raw.sources)?raw.sources:Array.isArray(raw.source_notes)?raw.source_notes:[];const sourceHtml=top.map(s=>{if(typeof s==='string')return/^https?:\/\//.test(s)?`<li><a href="${esc(s)}" target="_blank" rel="noopener noreferrer">${esc(s)}</a></li>`:`<li>${inline(s)}</li>`;if(!s||typeof s!=='object')return'';const label=s.title||s.publisher||s.url||'Source',detail=[s.publisher&&s.publisher!==label?s.publisher:'',s.date||''].filter(Boolean).join(' · ');return s.url?`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>${detail?` — ${esc(detail)}`:''}</li>`:`<li>${esc(label)}${detail?` — ${esc(detail)}`:''}</li>`}).filter(Boolean).join('');if(sourceHtml)sections.push({id:'sources',number:sections.length+1,title:'Sources',content:`<ul>${sourceHtml}</ul>`});return{schemaVersion:1,date:raw.date,title:raw.title||titleForDate(raw.date),readingTime:raw.readingTime||'10–15 min',sections}}
function recordedMusic(){const typed=[],numbered=[];for(const line of recorded.split(/\r?\n/)){let m=line.match(/(?:^[-*]\s+)?(?:\*\*)?(Classical|Jazz|Other)\b.*?(\d{1,2})\/10(?:\.?\*\*)?\.?\s*(.*)$/i);if(m){typed.push({type:m[1].toLowerCase(),rating:+m[2],commentary:m[3].trim()||null});continue}m=line.match(/^\d+\.\s+.*?(\d{1,2})\/10(?:\.?\*\*)?\.?\s*(.*)$/);if(m)numbered.push({rating:+m[1],commentary:m[2].trim()||null})}if(typed.length)return typed;const types=['classical','jazz','other'],set=numbered.slice(-3);return set.map((x,i)=>({type:types[i],...x}))}
function saved(d){let local={};try{local=JSON.parse(localStorage.getItem(key(d)))||{}}catch{}const defaults={music_feedback:recordedMusic()};return{...defaults,...local,music_feedback:local.music_feedback?.length?local.music_feedback:defaults.music_feedback}}
function collect(){if(!brief)return null;const section_feedback=brief.sections.map(s=>({section_id:s.id,section_title:s.title,feedback:nullable($(`[data-section-feedback="${s.id}"]`)?.value)}));const ms=brief.sections.find(s=>s.id==='music');const music_feedback=ms?.items?.map(i=>{const r=$(`[data-rating="${i.type}"]`),c=$(`[data-music-commentary="${i.type}"]`);return{type:i.type,label:i.label,piece:i.piece,url:i.url||null,rating:r?.dataset.touched==='true'?+r.value:null,commentary:nullable(c?.value)}})||[];return{schema_version:1,source:'egeeken.github.io/extras/demos/gpt-daily-brief',brief_date:brief.date,brief_title:brief.title,exported_at:new Date().toISOString(),section_feedback,music_feedback,overall_feedback:nullable(overall.value)}}
function save(){if(!brief)return;try{localStorage.setItem(key(brief.date),JSON.stringify(collect()));exportStatus.textContent='Saved locally.';setTimeout(()=>{if(exportStatus.textContent==='Saved locally.')exportStatus.textContent=''},1200)}catch{exportStatus.textContent='Local autosave is unavailable in this browser.'}}
const schedule=()=>{clearTimeout(timer);timer=setTimeout(save,250)};
function feedbackBox(s,data){const box=document.createElement('div');box.className='feedback-box';box.innerHTML=`<label>Section feedback <span>(optional)</span><textarea rows="3" data-section-feedback="${esc(s.id)}" placeholder="What do you think?"></textarea></label>`;const t=box.querySelector('textarea');t.value=data.section_feedback?.find(x=>x.section_id===s.id)?.feedback||'';t.addEventListener('input',schedule);return box}
function card(i,data){const prior=data.find(x=>x.type===i.type)||{},stored=Number.isFinite(prior.rating)?prior.rating:i.recordedRating,rating=Number.isFinite(stored)?stored:5,touched=Number.isFinite(stored),c=document.createElement('article');c.className=`music-card${i.videoId?'':' no-player'}`;c.innerHTML=`${i.videoId?`<div class="player-frame"><iframe src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(i.videoId)}" title="${esc(i.piece)}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>`:''}<div class="music-card-content"><p class="track-type">${esc(i.label)}</p><h3>${esc(i.piece)}</h3>${i.performer?`<p class="performer">${esc(i.performer)}</p>`:''}${i.description?`<p class="track-description">${esc(i.description)}</p>`:''}</div><div class="track-feedback"><div class="rating-row"><label for="rating-${esc(i.type)}">Rating</label><input id="rating-${esc(i.type)}" type="range" min="0" max="10" step="1" value="${rating}" data-rating="${esc(i.type)}" data-touched="${touched}"><output class="rating-value">${touched?`${rating}/10`:'Not rated'}</output></div><button class="clear-rating" type="button">Clear rating</button><textarea rows="3" data-music-commentary="${esc(i.type)}" placeholder="What do you think?" aria-label="${esc(i.label)} commentary"></textarea></div>`;const r=c.querySelector('input'),o=c.querySelector('output'),t=c.querySelector('textarea'),b=c.querySelector('button');t.value=prior.commentary||'';r.addEventListener('input',()=>{r.dataset.touched='true';o.textContent=`${r.value}/10`;schedule()});t.addEventListener('input',schedule);b.addEventListener('click',()=>{r.dataset.touched='false';r.value='5';o.textContent='Not rated';schedule()});return c}
function renderSection(s,data){const a=document.createElement('article');a.className='brief-section';a.id=`section-${s.id}`;a.innerHTML=`<div class="section-heading"><span class="section-number">${s.number}</span><div><h2>${s.title}</h2>${s.subtitle?`<p class="section-subtitle">${s.subtitle}</p>`:''}</div></div>`;const body=document.createElement('div');body.className='section-body';if(s.id==='music'&&s.items?.length){const intro=document.createElement('div');intro.className='music-intro';intro.innerHTML=`<div>${s.content||''}</div>${s.queue?`<a class="queue-button" href="${esc(s.queue)}" target="_blank" rel="noopener noreferrer">Open playlist queue ↗</a>`:''}`;body.append(intro);const grid=document.createElement('div');grid.className='music-grid';s.items.forEach(i=>grid.append(card(i,data.music_feedback||[])));body.append(grid)}else body.innerHTML=s.content||'';a.append(body,feedbackBox(s,data));return a}
function render(b){brief=b;const data=saved(b.date);document.title=`Ege — ${b.title}`;dateLabel.textContent=b.title;reading.textContent=b.readingTime||'';nav.replaceChildren(...b.sections.map(s=>{const a=document.createElement('a');a.href=`#section-${s.id}`;a.textContent=`${s.number}. ${s.title.replace(/^Two /,'')}`;return a}));if(recorded.trim()){recordedPanel.hidden=false;recordedPanel.innerHTML=`<details open><summary>Recorded feedback for this brief</summary><div class="recorded-feedback-body">${md(recorded)}</div></details>`}else{recordedPanel.hidden=true;recordedPanel.replaceChildren()}content.replaceChildren(...b.sections.map(s=>renderSection(s,data)));overall.value=data.overall_feedback||'';overall.oninput=schedule;status.hidden=true;content.hidden=false;exportPanel.hidden=false;exportStatus.textContent=''}
async function json(p){const r=await fetch(p,{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()}
async function text(p){const r=await fetch(p,{cache:'no-store'});return r.ok?r.text():''}
async function load(d){const rec=archive.briefs.find(x=>x.date===d);if(!rec)throw Error('Missing archive entry');status.hidden=false;status.classList.remove('error');status.textContent='Loading the brief…';content.hidden=true;recordedPanel.hidden=true;exportPanel.hidden=true;const [raw,fb]=await Promise.all([json(`data/${rec.file}`),rec.feedback?text(`data/${rec.feedback}`):'']);recorded=fb;render(normalise(raw))}
function fail(e){console.error(e);status.hidden=false;status.classList.add('error');status.textContent='The brief could not be loaded. The archive data may be temporarily unavailable.';content.hidden=true;recordedPanel.hidden=true;exportPanel.hidden=true}
function exportFeedback(){const p=collect();if(!p)return;const blob=new Blob([`${JSON.stringify(p,null,2)}\n`],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gpt-daily-brief-feedback-${brief.date}.json`;document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url);exportStatus.textContent=`Exported feedback for ${brief.date}.`;save()}
clearBtn.addEventListener('click',()=>{if(!brief||!confirm(`Clear all locally saved feedback for ${brief.date}? Recorded repository feedback will remain visible.`))return;localStorage.removeItem(key(brief.date));render(brief);exportStatus.textContent='Local feedback cleared.'});exportBtn.addEventListener('click',exportFeedback);
(async()=>{try{archive=await json('data/index.json');sel.replaceChildren(...archive.briefs.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>{const o=document.createElement('option');o.value=x.date;o.textContent=x.title||titleForDate(x.date);return o}));sel.disabled=false;sel.addEventListener('change',async()=>{try{await load(sel.value);history.replaceState(null,'',`?date=${encodeURIComponent(sel.value)}`)}catch(e){fail(e)}});const q=new URLSearchParams(location.search).get('date'),d=archive.briefs.some(x=>x.date===q)?q:archive.latest;sel.value=d;await load(d)}catch(e){fail(e)}})();
})();
